version: "3"
services:
  service-discovery-server:
    image: consul
    command: "agent -server -bootstrap"
  service-discovery-agent1:
    image: consul
    ports:
      - "8500:8500"
    command: "agent -join service-discovery-server -client 0.0.0.0 -ui"
    depends_on:
      - service-discovery-server
  service-discovery-agent2:
    image: consul
    command: "agent -join service-discovery-server -client 0.0.0.0"
    depends_on:
      - service-discovery-server
  api-gateway-rate-limiter-cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
  authentication-service-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: auth
      MONGO_INITDB_ROOT_PASSWORD: authpassword
      MONGO_INITDB_DATABASE: authdb
    ports:
      - 27017:27017
    volumes:
      - authentication_db_data_vol:/data/db

volumes:
  authentication_db_data_vol: